# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(443, 166)
        font = QtGui.QFont()
        font.setFamily("更纱黑体 UI HC Medium")
        Form.setFont(font)
        Form.setWindowTitle("")
        self.title_label = QtWidgets.QLabel(Form)
        self.title_label.setGeometry(QtCore.QRect(120, 30, 251, 31))
        font = QtGui.QFont()
        font.setFamily("更纱黑体 UI HC Medium")
        font.setPointSize(12)
        self.title_label.setFont(font)
        self.title_label.setText("")
        self.title_label.setObjectName("title_label")
        self.detail_label = QtWidgets.QLabel(Form)
        self.detail_label.setGeometry(QtCore.QRect(50, 70, 361, 71))
        font = QtGui.QFont()
        font.setFamily("更纱黑体 UI HC Medium")
        font.setPointSize(11)
        self.detail_label.setFont(font)
        self.detail_label.setText("")
        self.detail_label.setWordWrap(True)
        self.detail_label.setOpenExternalLinks(False)
        self.detail_label.setObjectName("detail_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass
